-- Blinda Bolsa Família — analytics do quiz
-- Execute este SQL no Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.quiz_sessions (
  id uuid primary key default gen_random_uuid(),
  session_id text not null unique,
  visitor_id text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  current_step integer not null default 1,
  landing_path text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text,
  device_type text
);

alter table public.quiz_sessions add column if not exists visitor_id text;
alter table public.quiz_sessions add column if not exists device_type text;

create table if not exists public.quiz_answers (
  id uuid primary key default gen_random_uuid(),
  session_id text not null references public.quiz_sessions(session_id) on delete cascade,
  question_id integer not null,
  answer text not null,
  answered_at timestamptz not null default now(),
  unique (session_id, question_id)
);

create table if not exists public.respostas_quiz (
  id bigint generated by default as identity primary key,
  nome text,
  idade numeric,
  estado text,
  cidade text,
  resposta_1 text,
  resposta_2 text,
  resposta_3 text,
  resposta_4 text,
  resposta_5 text,
  resposta_6 text,
  resposta_7 text,
  resposta_8 text,
  resultado text,
  created_at timestamptz not null default now()
);

alter table public.respostas_quiz add column if not exists resposta_6 text;
alter table public.respostas_quiz add column if not exists resposta_7 text;
alter table public.respostas_quiz add column if not exists resposta_8 text;
alter table public.respostas_quiz add column if not exists created_at timestamptz not null default now();

create index if not exists quiz_sessions_visitor_id_idx on public.quiz_sessions(visitor_id);
create index if not exists quiz_answers_session_id_idx on public.quiz_answers(session_id);
create index if not exists quiz_answers_question_id_idx on public.quiz_answers(question_id);
create index if not exists respostas_quiz_created_at_idx on public.respostas_quiz(created_at);

alter table public.quiz_sessions enable row level security;
alter table public.quiz_answers enable row level security;
alter table public.respostas_quiz enable row level security;

drop policy if exists "quiz sessions public insert" on public.quiz_sessions;
create policy "quiz sessions public insert" on public.quiz_sessions for insert to anon with check (true);

drop policy if exists "quiz sessions public update" on public.quiz_sessions;
create policy "quiz sessions public update" on public.quiz_sessions for update to anon using (true) with check (true);

drop policy if exists "quiz answers public insert" on public.quiz_answers;
create policy "quiz answers public insert" on public.quiz_answers for insert to anon with check (true);

drop policy if exists "quiz answers public update" on public.quiz_answers;
create policy "quiz answers public update" on public.quiz_answers for update to anon using (true) with check (true);

drop policy if exists "respostas quiz public insert" on public.respostas_quiz;
create policy "respostas quiz public insert" on public.respostas_quiz for insert to anon with check (true);

revoke select on public.quiz_sessions from anon;
revoke select on public.quiz_answers from anon;
revoke select on public.respostas_quiz from anon;

create table if not exists public.quiz_events (
  id uuid primary key default gen_random_uuid(),
  session_id text not null references public.quiz_sessions(session_id) on delete cascade,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists quiz_events_session_id_idx on public.quiz_events(session_id);
create index if not exists quiz_events_event_name_idx on public.quiz_events(event_name);
create index if not exists quiz_events_created_at_idx on public.quiz_events(created_at);

alter table public.quiz_events enable row level security;

drop policy if exists "quiz events public insert" on public.quiz_events;
create policy "quiz events public insert" on public.quiz_events for insert to anon with check (true);

revoke select on public.quiz_events from anon;

grant insert on public.quiz_sessions to anon;
grant update on public.quiz_sessions to anon;
grant insert on public.quiz_answers to anon;
grant update on public.quiz_answers to anon;
grant insert on public.quiz_events to anon;
grant insert on public.respostas_quiz to anon;

-- Endpoint seguro para registrar a conclusão.
-- Ele valida que a sessão existe antes de gravar o evento.
create or replace function public.record_quiz_completion(p_session_id text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1
    from public.quiz_sessions
    where session_id = p_session_id
  ) then
    return false;
  end if;

  insert into public.quiz_events (
    session_id,
    event_name,
    metadata
  )
  values (
    p_session_id,
    'quiz_completed',
    '{}'::jsonb
  );

  update public.quiz_sessions
  set completed_at = coalesce(completed_at, now()),
      current_step = 8
  where session_id = p_session_id;

  return true;
end;
$$;

revoke all on function public.record_quiz_completion(text) from public;
grant execute on function public.record_quiz_completion(text) to anon;

-- Limpa todos os dados acumulados durante os testes.
-- Use somente quando estiver pronto para começar a coleta real.
create or replace function public.reset_analytics_data()
returns boolean
language plpgsql
security definer
set search_path = public
as $
begin
  delete from public.respostas_quiz;
  delete from public.quiz_sessions;
  return true;
end;
$;

revoke all on function public.reset_analytics_data() from public;
grant execute on function public.reset_analytics_data() to anon;

-- Analytics: funil por sessão, com métricas de visitantes únicos separadas.
create or replace view public.analytics_funnel_overview as
with completed_sessions as (
  select distinct session_id from public.quiz_events where event_name = 'quiz_completed'
),
result_sessions as (
  select distinct e.session_id
  from public.quiz_events e
  inner join completed_sessions c on c.session_id = e.session_id
  where e.event_name = 'result_viewed'
),
checkout_sessions as (
  select distinct e.session_id
  from public.quiz_events e
  inner join result_sessions r on r.session_id = e.session_id
  where e.event_name = 'checkout_click'
),
started_visitors as (
  select distinct qs.visitor_id
  from public.quiz_sessions qs
  inner join public.quiz_events e on e.session_id = qs.session_id
  where e.event_name = 'quiz_started' and qs.visitor_id is not null
),
completed_visitors as (
  select distinct qs.visitor_id
  from public.quiz_sessions qs
  inner join completed_sessions c on c.session_id = qs.session_id
  where qs.visitor_id is not null
),
result_visitors as (
  select distinct qs.visitor_id
  from public.quiz_sessions qs
  inner join result_sessions r on r.session_id = qs.session_id
  where qs.visitor_id is not null
),
checkout_visitors as (
  select distinct qs.visitor_id
  from public.quiz_sessions qs
  inner join checkout_sessions c on c.session_id = qs.session_id
  where qs.visitor_id is not null
),
cta_visitors as (
  select distinct qs.visitor_id
  from public.quiz_sessions qs
  inner join public.quiz_events e on e.session_id = qs.session_id
  where e.event_name = 'cta_click' and qs.visitor_id is not null
)
select
  (select count(*) from public.quiz_sessions)::bigint as visitors,
  (select count(distinct session_id) from public.quiz_events where event_name = 'quiz_started')::bigint as quiz_starts,
  (select count(*) from completed_sessions)::bigint as quiz_completions,
  (select count(*) from result_sessions)::bigint as result_views,
  (select count(*) from checkout_sessions)::bigint as checkout_clicks,
  (select count(distinct session_id) from public.quiz_events where event_name = 'cta_click')::bigint as cta_clicks,
  (select count(*) from started_visitors)::bigint as unique_quiz_starters,
  (select count(*) from completed_visitors)::bigint as unique_quiz_completions,
  (select count(*) from result_visitors)::bigint as unique_result_viewers,
  (select count(*) from checkout_visitors)::bigint as unique_checkout_visitors,
  (select count(*) from cta_visitors)::bigint as unique_cta_visitors;

grant select on public.analytics_funnel_overview to anon;

create or replace view public.analytics_visitors_overview as
with counts as (
  select
    count(*)::bigint as total_visitors,
    count(distinct visitor_id)::bigint as unique_visitors,
    count(distinct visitor_id) filter (where started_at::date = current_date)::bigint as visitors_today,
    count(distinct visitor_id) filter (where started_at >= now() - interval '7 days')::bigint as visitors_7d,
    count(distinct visitor_id) filter (where started_at >= now() - interval '30 days')::bigint as visitors_30d,
    (select count(distinct session_id) from public.quiz_events where event_name = 'quiz_started')::bigint as quiz_starts,
    (select count(distinct session_id) from public.quiz_events where event_name = 'quiz_completed')::bigint as completed_quizzes
  from public.quiz_sessions
)
select
  total_visitors,
  unique_visitors,
  visitors_today,
  visitors_7d,
  visitors_30d,
  completed_quizzes,
  greatest(quiz_starts - completed_quizzes, 0)::bigint as unfinished_quizzes
from counts;

create or replace view public.analytics_visitors_daily as
select
  started_at::date as day,
  count(distinct visitor_id)::bigint as visitors
from public.quiz_sessions
where started_at >= current_date - interval '29 days'
group by started_at::date
order by day;

grant select on public.analytics_visitors_overview to anon;
grant select on public.analytics_visitors_daily to anon;


-- Relatórios de aquisição e dispositivo.
create or replace view public.analytics_traffic_sources as
select
  coalesce(nullif(utm_source, ''), 'Direto / não identificado') as source,
  coalesce(nullif(utm_medium, ''), '—') as medium,
  count(distinct visitor_id)::bigint as unique_visitors,
  count(*)::bigint as sessions
from public.quiz_sessions
group by 1, 2
order by unique_visitors desc, sessions desc;

create or replace view public.analytics_devices as
select
  coalesce(nullif(device_type, ''), 'unknown') as device,
  count(distinct visitor_id)::bigint as unique_visitors,
  count(*)::bigint as sessions
from public.quiz_sessions
group by 1
order by unique_visitors desc, sessions desc;

grant select on public.analytics_traffic_sources to anon;
grant select on public.analytics_devices to anon;
