-- Blinda Bolsa Família — analytics do quiz
-- Execute este SQL no Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.quiz_sessions (
  id uuid primary key default gen_random_uuid(),
  session_id text not null unique,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  current_step integer not null default 1,
  landing_path text,
  referrer text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_content text,
  utm_term text
);

create table if not exists public.quiz_answers (
  id uuid primary key default gen_random_uuid(),
  session_id text not null references public.quiz_sessions(session_id) on delete cascade,
  question_id integer not null,
  answer text not null,
  answered_at timestamptz not null default now(),
  unique (session_id, question_id)
);

create table if not exists public.respostas_quiz (
  id bigint generated by default as identity primary key,
  nome text,
  idade numeric,
  estado text,
  cidade text,
  resposta_1 text,
  resposta_2 text,
  resposta_3 text,
  resposta_4 text,
  resposta_5 text,
  resposta_6 text,
  resposta_7 text,
  resposta_8 text,
  resultado text,
  created_at timestamptz not null default now()
);

alter table public.respostas_quiz add column if not exists resposta_6 text;
alter table public.respostas_quiz add column if not exists resposta_7 text;
alter table public.respostas_quiz add column if not exists resposta_8 text;
alter table public.respostas_quiz add column if not exists created_at timestamptz not null default now();

create index if not exists quiz_answers_session_id_idx on public.quiz_answers(session_id);
create index if not exists quiz_answers_question_id_idx on public.quiz_answers(question_id);
create index if not exists respostas_quiz_created_at_idx on public.respostas_quiz(created_at);

alter table public.quiz_sessions enable row level security;
alter table public.quiz_answers enable row level security;
alter table public.respostas_quiz enable row level security;

drop policy if exists "quiz sessions public insert" on public.quiz_sessions;
create policy "quiz sessions public insert" on public.quiz_sessions for insert to anon with check (true);

drop policy if exists "quiz sessions public update" on public.quiz_sessions;
create policy "quiz sessions public update" on public.quiz_sessions for update to anon using (true) with check (true);

drop policy if exists "quiz answers public insert" on public.quiz_answers;
create policy "quiz answers public insert" on public.quiz_answers for insert to anon with check (true);

drop policy if exists "quiz answers public update" on public.quiz_answers;
create policy "quiz answers public update" on public.quiz_answers for update to anon using (true) with check (true);

drop policy if exists "respostas quiz public insert" on public.respostas_quiz;
create policy "respostas quiz public insert" on public.respostas_quiz for insert to anon with check (true);

revoke select on public.quiz_sessions from anon;
revoke select on public.quiz_answers from anon;
revoke select on public.respostas_quiz from anon;


create table if not exists public.quiz_events (
  id uuid primary key default gen_random_uuid(),
  session_id text not null references public.quiz_sessions(session_id) on delete cascade,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists quiz_events_session_id_idx on public.quiz_events(session_id);
create index if not exists quiz_events_event_name_idx on public.quiz_events(event_name);
create index if not exists quiz_events_created_at_idx on public.quiz_events(created_at);

alter table public.quiz_events enable row level security;

drop policy if exists "quiz events public insert" on public.quiz_events;
create policy "quiz events public insert" on public.quiz_events for insert to anon with check (true);

revoke select on public.quiz_events from anon;

-- Permissões explícitas para o papel público usado pelo frontend.
grant insert on public.quiz_sessions to anon;
grant update on public.quiz_sessions to anon;
grant insert on public.quiz_answers to anon;
grant update on public.quiz_answers to anon;
grant insert on public.quiz_events to anon;
grant insert on public.respostas_quiz to anon;

-- Painel agregado do funil
create or replace view public.analytics_funnel_overview as
select
  (select count(*) from public.quiz_sessions)::bigint as visitors,
  (select count(*) from public.quiz_events where event_name = 'quiz_started')::bigint as quiz_starts,
  (select count(distinct session_id) from public.quiz_events where event_name = 'quiz_completed')::bigint as quiz_completions,
  (select count(*) from public.quiz_events where event_name = 'result_viewed')::bigint as result_views,
  (select count(*) from public.quiz_events where event_name = 'checkout_click')::bigint as checkout_clicks,
  (select count(*) from public.quiz_events where event_name = 'cta_click')::bigint as cta_clicks;

grant select on public.analytics_funnel_overview to anon;


-- Painel agregado de visitantes (não expõe dados individuais)
create or replace view public.analytics_visitors_overview as
select
  count(*)::bigint as total_visitors,
  count(*) filter (where started_at::date = current_date)::bigint as visitors_today,
  count(*) filter (where started_at >= now() - interval '7 days')::bigint as visitors_7d,
  count(*) filter (where started_at >= now() - interval '30 days')::bigint as visitors_30d,
  (select count(distinct session_id) from public.quiz_events where event_name = 'quiz_completed')::bigint as completed_quizzes,
  (count(*) - (select count(distinct session_id) from public.quiz_events where event_name = 'quiz_completed'))::bigint as unfinished_quizzes
from public.quiz_sessions;

create or replace view public.analytics_visitors_daily as
select
  started_at::date as day,
  count(*)::bigint as visitors
from public.quiz_sessions
where started_at >= current_date - interval '29 days'
group by started_at::date
order by day;

grant select on public.analytics_visitors_overview to anon;
grant select on public.analytics_visitors_daily to anon;
