-- Final clean slate before real traffic.
-- After this migration, analytics contains only visits/events generated by real users.
delete from public.respostas_quiz;
delete from public.quiz_events;
delete from public.quiz_answers;
delete from public.quiz_sessions;

notify pgrst, 'reload schema';
